<!--bind:data-navigator-->
<div class="vendors-navigator-panel">
    <div class="col base small breadcrumbs">
        <div class="col crumb"><a href="/operators/home"><?=\gear\Core::app()->controllers->currentController->caption?></a></div>
        <div class="col crumb arrow">&gt;</div>
        <div class="col crumb last">Поставщики</div>
    </div>
    <div class="coll pull-right base light small paginator text-center">
        <div class="col bold page" title="Назад">&lt;</div>
        <div class="col bold page" title="Вперёд">&gt;</div>
        <div class="col page">1</div>
        <div class="col page">...</div>
        <div class="col page">8</div>
        <div class="col page selected">9</div>
        <div class="col page">10</div>
        <div class="col page">11</div>
        <div class="col page">12</div>
        <div class="col page">...</div>
        <div class="col page">30</div>
    </div>
</div>
