<!--bind:data-toolbar-->
<div class="vendors-toolbar-panel">
    <?= isset($caption) && $caption ? "<div class=\"col pc-2 pull-left base light big toolbar-caption\">$caption</div>" : '' ?>
    <div class="col pull-left toolbar-buttons">
        <div class="base light small pull-left button toolbar toolbars-menu hidden-pc hidden-nt visible-tb visible-mb">
            <div class="fly toolbar-menu-items hide">
                <div class="button toolbar item add">новый заказ</div>
                <div class="button toolbar item remove">удалить</div>
            </div>
        </div>
        <div class="base light small pull-left button toolbar add hidden-tb hidden-mb">новый заказ</div>
        <div class="base light small pull-left button toolbar remove hidden-tb hidden-mb">удалить</div>
    </div>
    <div class="col pull-right toolbar-sort">
        <div class="base light small pull-left button toolbar sort desc">по дате заказа</div>
        <div class="base light small pull-left button toolbar sort">по статусу</div>
    </div>
</div>