<?php foreach($array as $name => $value) 
{ 
    if (is_array($value)) 
    { 
        echo str_repeat(' ', $tab) , "'$name' => array\n", str_repeat(' ', $tab), "(\n" , $this->render('\\gear\\builder\\templates\\config.arr.phtml', array('array' => $value, 'tab' => $tab + 4), true), str_repeat(' ', $tab), "),\n";
    } 
    else 
    { 
        echo str_repeat(' ', $tab), "'$name' => '" . $this->prepareValue($value) . "',\n";
    }
} ?>