<?php

/**
 * Шаблон страниц
 *
 * @package Gear Framework
 * @author Kukushkin Denis
 * @copyright 2023 Kukushkin Denis
 * @license http://www.spdx.org/licenses/MIT MIT License
 * @since 3.0.0
 * @version 3.0.0
 *
 * @var string $layoutContent
 */
?>
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <title><?=$this->title?></title>
    </head>

    <body>
        <h1>Layout</h1>
        <article><?=$layoutContent?></article>
    </body>

</html>
