<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <title><?=$this->caption?></title>
    </head>

    <body>
        <h1 class="base light big text-center base-color">Ошибка аутентификации оператора, через 5 секунд вы будете переведены на страницу для повторного ввода имени пользователя и пароля...</h1>
        <div id="counter" class="base light xxxl text-center base-color">5 сек.</div>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic" rel="stylesheet">
        <?=\gear\Core::m('resources')->publicate('framework.css')?>
        <?=\gear\Core::m('resources')->publicate('jquery-3.1.1.min.js')?>
        <?=\gear\Core::m('resources')->publicate('operators/auth.css')?>
        <script>
            $(document).ready(function() {
                var counter = 5;
                var h = function() {
                    counter --;
                    $('#counter').text(counter + ' сек.');
                    t();
                };
                var t = function() {
                    if (counter >= 1) {
                        setTimeout(h, 1000);
                    } else {
                        self.location = '/<?=$this->getModule()->authController?>';
                    }
                };
                t();
            });
        </script>
    </body>

</html>