<div class="top">
    <div class="top-area">
        <div class="logo-area"></div>
    </div>
</div>
<form method="post" action="<?=\HtmlHelper::url(\gear\Core::m('operators')->i('loginController'), 'login')?>">
    <h2>Authentificate operator</h2>
    <p>Username <input type="text" name="username" id="username"></p>
    <p>Password <input type="password" name="password" id="password"></p>
    <input type="submit" value="Apply" name="apply" id="apply">
</form>