<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <title><?=$this->caption?></title>
    </head>
    <body>
        <div class="container pc-12">
            <div class="row">
                <div class="col pc-1 light big"></div>
                <div class="col pc-10 light xlbig text-uppercase"><?=$this->caption?></div>
                <div class="col pc-1 light big"></div>
            </div>
        </div>
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,700&amp;subset=cyrillic" rel="stylesheet">
        <link href="/css/framework.css" rel="stylesheet" type="text/css" />
        <script src="/js/jquery-3.1.1.min.js"></script>
    </body>
</html>