<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <title><?=$this->caption?></title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic" rel="stylesheet">
        <script src="/js/jquery-3.1.1.min.js"></script>
    </head>
    <body>
    <div class="top">
        <div class="top-area">
            <div class="logo-area"></div>
            <div class="search-area">
                <input type="text">
            </div>
            <div class="basket-area"><div class="text-main">Корзина</div><div class="text-sub">пусто</div></div>
            <div class="client-area"><div class="text-main">Кабинет</div><div class="text-sub">войти</div></div>
        </div>
        <div class="mainmenu-area base extrabold text-uppercase small">
            <div id="boards" class="main-item selected">платы</div>
            <div id="modules" class="main-item">модули</div>
            <div id="sensors" class="main-item">датчики</div>
            <div id="displays" class="main-item">экраны</div>
            <div id="powers" class="main-item">питание</div>
            <div id="radio" class="main-item">радиодетали</div>
            <div id="tech" class="main-item">механика</div>
            <div id="others" class="main-item">разное</div>
            <div id="libraries" class="main-item">библиотеки</div>
        </div>
        <div class="submenu-area">
            <div class="submenu-items modules base bold text-uppercase text-center small">
                <div class="submenu-item pull-left">Arduino</div>
                <div class="submenu-item pull-left">Banana Pi</div>
                <div class="submenu-item pull-left">BeagleBoard</div>
                <div class="submenu-item pull-left">Orange Pi</div>
                <div class="submenu-item pull-left">Raspberry Pi</div>
                <div class="clearfix"></div>
            </div>
            <div class="submenu-items modules base bold text-uppercase text-center small hidden">
                <div class="submenu-item">Bluetooth</div>
                <div class="submenu-item">Ethernet</div>
                <div class="submenu-item">GSM/GRPS</div>
                <div class="submenu-item">Wi-Fi</div>
                <div class="submenu-item">XBee</div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic" rel="stylesheet">
    <?=\gear\Core::m('resources')->publicate('resources/css/framework.css')?>
    <?=\gear\Core::m('resources')->publicate('resources/css/base.css')?>
    </body>
</html>