<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <title><?=$this->caption?></title>
    </head>

    <body>
        <div class="top">
            <?= $this->view->render($this->viewPath . '/../common/mainmenu'); ?>
        </div>

        <?=$contentLayout?>

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic" rel="stylesheet">
        <?=\gear\Core::m('resources')->publicate('resources/css/framework.css')?>
        <?=\gear\Core::m('resources')->publicate('resources/css/operators/base.css')?>
        <?=\gear\Core::m('resources')->publicate('resources/js/jquery-3.1.1.min.js')?>
        <?=\gear\Core::m('resources')->publicate('resources/js/objectClass.js')?>
        <?=\gear\Core::m('resources')->publicate('resources/js/app.js')?>
        <?=\gear\Core::m('resources')->publicate('resources/js/request.js')?>
        <?=\gear\Core::m('resources')->publicate('resources/js/mainMenu.js')?>
    </body>

</html>