<div class="top-area">
    <div class="logo-area"></div>
</div>
<div id="mainMenu">
    <div class="mainmenu-area base extrabold text-uppercase small">
        <div id="supply" class="main-item">поставки</div>
        <div id="storage" class="main-item">склад</div>
        <div id="clients" class="main-item">клиенты</div>
        <div id="reports" class="main-item">отчёты</div>
    </div>
    <div class="submenu-area">
        <div class="submenu-items supply base bold text-uppercase text-center small hidden">
            <div id="arduino" class="submenu-item pull-left" data-action="operators/vendors">поставщики</div>
            <div id="banana" class="submenu-item pull-left" data-action="operators/vendorOrders">закупки</div>
            <div class="clearfix"></div>
        </div>
        <div class="submenu-items storage base bold text-uppercase text-center small hidden">
            <div class="submenu-item pull-left">склад</div>
            <div class="clearfix"></div>
        </div>
        <div class="submenu-items clients base bold text-uppercase text-center small hidden">
            <div class="submenu-item pull-left">клиенты</div>
            <div class="submenu-item pull-left">заказы</div>
            <div class="clearfix"></div>
        </div>
        <div class="submenu-items reports base bold text-uppercase text-center small hidden">
            <div class="submenu-item pull-left">доходы</div>
            <div class="submenu-item pull-left">расходы</div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
